GPT-16 frontend app multistage build dockerfile
apapadaki/miniChatGPT pull request #4
Opened 2023-03-05 15:08 UTC by chiknas

2023-04-06 19:32 UTC, apapadaki requested changes

2023-04-06 19:32 UTC, apapadaki commented on application/frontend/README.md
> +docker build . -t minichatgpt/frontend
add the exact  directory that this should run

2023-05-08 13:17 UTC, chiknas commented on application/frontend/README.md
> +docker build . -t minichatgpt/frontend
done

2023-05-09 12:45 UTC, apapadaki approved these changes

2023-05-09 12:45 UTC, merged